### PR TITLE
Bump TCPDF version

### PR DESCRIPTION
**Pull request by phena109**
TCPDF have version 6.3.* created and one of them addresses 1 PHP7.4 issue.

### CODE REVIEW

**Review by JanSlabon — COMMENTED** [review]
This is a no-go, sorry.

**Comment by JanSlabon** [comment]
Sorry but it looks like you build your own version/package now, which is fine but I am closing this one and bump the version in the near future manually.

**Comment by JanSlabon** [comment]
Just for completion: The dependency is already set to "^6.2" which also covers 6.3. For more details please read [this](https://getcomposer.org/doc/articles/versions.md#caret-version-range-).

**Comment by phena109** [comment]
Terribly sorry for the noob work in the pull request. The subsequent commits were not really intended for this PR. 
Thanks for telling me the info. I learn a a good lesson from this. :)

**Comment by JanSlabon** [comment]
All well :-)

**Pull request closed without merging**
